# Codecov

coverage:
  status:
    project:
      default:
        target: 1
    patch:
      default:
        target: 0

github_checks:
  annotations: false

ignore:
  - 'conftest.py'
  - '**/tests/*.py'
  - 'python/optiprofiler/utils.py'
